---
- name: Make monitoring root dir
  ansible.builtin.file:
    path: /opt/monitoring
    state: directory
    mode: "0755"
- name: Deploy prometheus.yml
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /opt/monitoring/prometheus.yml
    mode: "0644"
  notify: Restart docker compose
- name: Deploy grafana_sources.yml
  ansible.builtin.copy:
    src: grafana_sources.yml
    dest: /opt/monitoring/grafana_sources.yml
    mode: "0644"
  notify: Restart docker compose
- name: Deploy docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /opt/monitoring/docker-compose.yml
    mode: "0644"
  notify: Restart docker compose
- name: Install docker-compose
  ansible.builtin.apt:
    update_cache: true
    name:
      - docker-compose
    install_recommends: false
    autoremove: true
    autoclean: true
  # TODO: 内部的にdocker-composeを使用しているので、
  #       module更新され次第docker composeに置き換え
- name: Start monitoring
  community.docker.docker_compose:
    project_src: /opt/monitoring
