all:
  children:
    prometheus_server:
      hosts:
        prometheus_server1:
          ansible_host: localhost
          ansible_user: tom
          ansible_become_password: pass
          ansible_password: pass
    targets:
      hosts:
        main_pc:
          ansible_host: localhost
          ansible_user: tom
          ansible_become_password: pass
          ansible_password: pass
        zero:
          ansible_user: tom
          ansible_host: 192.168.12.101
          ansible_become_password: pass
          ansible_password: pass
