all:
  children:
    control:
      hosts:
        localhost:
          ansible_host: localhost
          ansible_connection: local
    target:
      hosts:
        localhost:
          ansible_host: localhost
          ansible_connection: local
