all:
  children:
    prometheus_server:
      hosts:
        prometheus_server:
          ansible_host: 192.168.11.107
    target:
      hosts:
        localhost:
          ansible_host: localhost
          ansible_connection: local
