all:
  children:
    prometheus_server:
      hosts:
        prometheus_server1:
          ansible_host: localhost
          ansible_user: tom
          ansible_become_password: pass
          ansible_password: pass
    targets:
      hosts:
        main_pc:
          ansible_host: localhost
          ansible_user: tom
          ansible_become_password: pass
          ansible_password: pass
    local:
      hosts:
        localhost:
          ansible_connection: local
          # TODO: control nodeではsudo権限要求しないよう変更
          ansible_become_password: pass
