all:
  children:
    prometheus_server:
      hosts:
        prometheus_server:
          ansible_host: localhost
          # ansible_user: user
          # ansible_pass: pass
    targets:
      hosts:
        main_pc:
          ansible_host: localhost
          # ansible_user: user
          # ansible_pass: pass
